-- Supabase / SQL schema for MVP v2

create table if not exists models (
  id bigint generated by default as identity primary key,
  model_name text not null,
  provider text,
  category text,
  open_source_status text,
  free_tier_status text,
  strengths jsonb,
  weaknesses jsonb,
  total_score int,
  status text default 'candidate',
  created_at timestamp default now()
);

create table if not exists evaluation_runs (
  id bigint generated by default as identity primary key,
  run_id text unique,
  report_path text,
  recommendations jsonb,
  created_at timestamp default now()
);

create table if not exists approval_requests (
  id bigint generated by default as identity primary key,
  request_id text unique,
  category text,
  old_model text,
  new_model text,
  reason text,
  human_decision text,
  created_at timestamp default now(),
  decision_at timestamp
);
